### PR TITLE
Fixes #50: Handle sorting of documents on multiple attributes

### LINKED ISSUE #50: Sorting documents by multiple attributes is not working correctly
## Problem
When we provide multiple `OrderBy`s in a query, it sometimes returns the documents in an incorrect order. For example, if we try to sort the documents based on `field1` and then `field2`, it works incorrectly in some cases:
`query.addAllOrderBys(List.of(new OrderBy("field1", true), new OrderBy("field2", false)));`

This is tested using MongoCollection.

## Cause
The orderBy list is converted to a HashMap which may not preserve the order of the keys(as in the list) -
https://github.com/hypertrace/document-store/blob/main/document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java#L365
So, in the above example, it can happen that the sorting happens first on `field2` and then on `field1`.

### PR DESCRIPTION
**Pull request by GurtejSohi**
## Description
Fixes https://github.com/hypertrace/document-store/issues/50 by using `LinkedHashMap` instead of `HashMap` for `orderByMap` to preserve the order of keys (as in the list).

### Testing
Added unit test

### Checklist:
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java [hunk 1]
```diff
@@ -409,10 +408,13 @@ public boolean deleteAll() {
     return true;
   }
 
-  private void parseOrderByQuery(List<OrderBy> orderBys, Map<String, Object> orderbyMap) {
+  @VisibleForTesting
+  LinkedHashMap<String, Object> parseOrderByQuery(List<OrderBy> orderBys) {
```
Comment (aaron-steinfeld) [inline document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java:412]: nit: perhaps a query parser util/class would better follow SRP and remove the need for `@VisibleForTesting`, everyone's favorite antipattern 😉

**Review by aaron-steinfeld — COMMENTED** [review]
lgtm

File: document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java [hunk 2]
```diff
@@ -409,10 +408,13 @@ public boolean deleteAll() {
...
+    LinkedHashMap<String, Object> orderByMap = new LinkedHashMap<>();
     for (OrderBy orderBy : orderBys) {
-      orderbyMap.put(orderBy.getField(), (orderBy.isAsc() ? 1 : -1));
+      orderByMap.put(orderBy.getField(), (orderBy.isAsc() ? 1 : -1));
```
Comment (kotharironak) [inline document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java:415]: Can you extend the test `testOffsetAndLimitOrderBy` with multiple orderBy in [DocStoreTest.java](https://github.com/hypertrace/document-store/blob/081cf1b5f9433e22d1a8736d01e1cc85dd663109/document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreTest.java#L827), so, it can verify Postgres side too. However, I have checked the Postgres side impl, it looks fine for multiple orderby.

**Review by kotharironak — COMMENTED** [review]
overall, lgtm.

File: document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java (hunk 1 above)
Comment (GurtejSohi) [reply document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java]: Moved the query parsing methods into QueryParser classes - one for mongo and another for postgres.

File: document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java (hunk 2 above)
Comment (GurtejSohi) [reply document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java]: Sure, extended that test to add multiple orderBys.
Also, added a unit test for `parseOrderBys` method for Postgres.

File: document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoQueryParser.java [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+          throw new UnsupportedOperationException(
+              String.format("Boolean operation:%s not supported", op));
+      }
+    } else {
+      Filter.Op op = filter.getOp();
+      Object value = filter.getValue();
+      Map<String, Object> map = new HashMap<>();
+      switch (op) {
+        case EQ:
+          map.put(filter.getFieldName(), value);
```
Comment (aaron-steinfeld) [inline document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoQueryParser.java:46]: Looks like this just got moved. The create/put/break/return kills me but that's probably scope creep.

**Review by aaron-steinfeld — APPROVED** [review]

**Review by kotharironak — APPROVED** [review]
